### ISSUE TITLE
検索画面のタブを作る。

### ISSUE THREAD

**Issue by greenmeganes** [megane-s/minshumi-frontend#114]
## 機能の説明

- 作品・ユーザ検索画面のURLが違う (正しくは`/search/art` , `/search/user`)ので直す
- 「作品」「ユーザ」を切り替えるタブを設置する

## 実装内容 または やること

 

- [x] 担当者を決める

## 進め方 方針

- [ ] ぱっと見でレビューする。 （比較的簡単な機能向け）
- [x] 必要に応じてペアプロしながら しっかりレビューする。 （相談・調整しながら仕上げていく機能向け）
- [ ] その他

## 参考文献

- [作品検索画面の画面設計](https://www.figma.com/file/CgUG7Ndac2D6JwWLdVo42i/%E3%81%BF%E3%82%93%E3%81%97%E3%82%85%E3%81%BF-%E7%94%BB%E9%9D%A2%E8%A8%AD%E8%A8%88?type=design&node-id=380-1000&mode=design&t=o49Io4wqUN0k7fGN-4)
- [ユーザ検索画面の画面設計](https://www.figma.com/file/CgUG7Ndac2D6JwWLdVo42i/%E3%81%BF%E3%82%93%E3%81%97%E3%82%85%E3%81%BF-%E7%94%BB%E9%9D%A2%E8%A8%AD%E8%A8%88?type=design&node-id=380-1002&mode=design&t=o49Io4wqUN0k7fGN-4)

**Comment by TBSten** [comment]
以下の資料を事前に読み進めておいてください。

- [ ] [Next.js13のLayoutsについて](https://note.com/lovely_acacia928/n/n9c522992b25b)
- [ ] [Next.js 13の新機能「App Router」でコンテンツ部分だけを更新する](https://codezine.jp/article/detail/18520)
- [ ] [Routing Fundamentals](https://nextjs.org/docs/app/building-your-application/routing)
- [ ] [Defining Routes](https://nextjs.org/docs/app/building-your-application/routing/defining-routes)
- [ ] [Pages and Layouts](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts)
