### ISSUE TITLE
placeholder画像の削除

### ISSUE THREAD

**Issue by TBSten** [megane-s/minshumi-frontend#196]
## 機能の説明

- publicディレクトリのプレースホルダ画像を削除
- プレースホルダ画像を使用していた箇所を別の本番用の画像に置き換え

## 実装内容 または やること

 

- [ ] 担当者を決める

## 進め方 方針

- [x] ぱっと見でレビューする。 （比較的簡単な機能向け）
- [ ] 必要に応じてペアプロしながら しっかりレビューする。 （相談・調整しながら仕上げていく機能向け）
- [ ] その他

## 参考文献

-

**Comment by TBSten** [comment]
基本的にはデフォルト画像は/placeholder配下の画像は使わないで、cloud storageに用意すると良さそう

**Comment by greenmeganes** [comment]
placeholder使われているところ(不備あるかもしれません)
- トップ画面の作品(https://minshumi.com/)
- 作品登録(https://minshumi.com/art/new/detail)
- 前後に見た作品(https://minshumi.com/art/clrg1a23n0006s601vuse78oe/appeal)
- 作品編集(https://minshumi.com/art/test-art-1/edit/detail)
- 作品詳細(https://minshumi.com/art/clrg1a23n0006s601vuse78oe)
- MYプロフィール(https://minshumi.com/user/clre7apax0000a3jocbxt08mp)
-
