### ISSUE TITLE
名刺作成ページの変更

### ISSUE THREAD

**Issue by greenmeganes** [megane-s/minshumi-frontend#237]
## 不具合の内容
名刺作成し公開したときのページがそのままなので、
0個から1個作成したときはデフォルトでプロフィール表示させたい。
それ以外は選択ページに遷移するようにする。

**Comment by TBSten** [comment]
@megane-s/frontend

現状 名刺の作成は名刺タイプを選んだ時だから、

> 0個から1個作成したときデフォルトでプロフィール表示する名刺として設定

じゃなくて

> 1.
> **公開ボタンが押された時に プロフィール画面に表示する名刺として設定されている名刺がなければそれをプロフィール画面に表示する名刺として設定する**
> またその場合あらかじめ公開ボタン付近にAlertなどで表示しておく。

> 2.
> 公開ボタンとは別に**「公開してプロフィール画面に表示」みたいなボタン or Switch（文言は別途相談したい）を置いてそれを押されたら公開 + プロフィール画面に表示する**みたいな感じにする
> 
> ボタン ver
> ![MacBook Air - 35](https://github.com/megane-s/minshumi-frontend/assets/81161390/d51d1545-323b-47a4-94df-4b3b97aaec6e)
> 
> Switch ver
> ![MacBook Air - 36](https://github.com/megane-s/minshumi-frontend/assets/81161390/5476d497-0e33-4b12-895c-d8444e364382)
> 

のどっちかが良さそうだよね？

**Comment by TBSten** [comment]
<img width="830" alt="スクリーンショット 2024-01-19 3 37 51" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/f55d2df2-c480-46f5-82c0-8b8d2241223f">


名刺じゃなくてユーザに対してコメントするように変更したから、「コメントを許可する」のSwitchいらなくなったよな...? 
ということでこのissueでついでに消しちゃおう

**Comment by TBSten** [comment]
> @megane-s/frontend
> 
> 現状 名刺の作成は名刺タイプを選んだ時だから、
> 
> > 0個から1個作成したときデフォルトでプロフィール表示する名刺として設定
> 
> じゃなくて
> 
> > **公開ボタンが押された時に プロフィール画面に表示する名刺として設定されている名刺がなければそれをプロフィール画面に表示する名刺として設定する**
> > またその場合あらかじめ公開ボタン付近にAlertなどで表示しておく。
> 
> > 公開ボタンとは別に **「公開してプロフィール画面に表示」みたいなボタン or Switch（文言は別途相談したい）を置いてそれを押されたら公開 + プロフィール画面に表示する** みたいな感じにする
> > ボタン ver
> > ![MacBook Air - 35](https://private-user-images.githubusercontent.com/81161390/297850339-d51d1545-323b-47a4-94df-4b3b97aaec6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzgyNzMsIm5iZiI6MTcwNTYzNzk3MywicGF0aCI6Ii84MTE2MTM5MC8yOTc4NTAzMzktZDUxZDE1NDUtMzIzYi00N2E0LTk0ZGYtNGIzYjk3YWFlYzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA0MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZTRjYmRmZDZiOTM2N2I0N2RlZDljZWFmZTY4MWFhYTRlZDgxMWFkNzgzMTUzZjcwNTI1YzBlNmUzYjJmODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jQcjwiengw0Ky4mGwH2OTsKFbiVVYt2XFyhJsdoEO6I)
> > Switch ver
> > ![MacBook Air - 36](https://private-user-images.githubusercontent.com/81161390/297850406-5476d497-0e33-4b12-895c-d8444e364382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzgyNzMsIm5iZiI6MTcwNTYzNzk3MywicGF0aCI6Ii84MTE2MTM5MC8yOTc4NTA0MDYtNTQ3NmQ0OTctMGUzMy00YjEyLTg5NWMtZDg0NDRlMzY0MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA0MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZTkyNDBlYmM2ZDc3MWM4M2I0YzM5Y2JlM2JlZDcyNTFhNzUxNzg3NDhjZDk2OWMyOGYzNzIyMzg1ODcwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oy9b1vMt0Snop2hXRY-OWoqStKJHHgbqkvNdcL47XL0)
> 
> のどっちかが良さそうだよね？

2のSwitchにする
