### ISSUE TITLE
作品アピール編集で他の人が登録した前後に見た作品出てくる

### ISSUE THREAD

**Issue by daisonmeganes** [megane-s/minshumi-frontend#239]
## 不具合の内容
![スクリーンショット 2024-01-17 160902](https://github.com/megane-s/minshumi-frontend/assets/148510436/a9d44041-df41-4d50-b094-6ccda4698d1f)

**Comment by TBSten** [comment]
`getRelatedArts()` model関数でユーザIDによる絞り込みしてないせいだこれ
