### ISSUE TITLE
各modelに権限に関する処理を追加する。

### ISSUE THREAD

**Issue by TBSten** [megane-s/minshumi-frontend#30]
## 機能の説明

権限に関する処理を実装していないので実装する。

## 実装内容 または やること

 

- [x] 担当者を決める -> @TBSten 
- [ ] どの機能(model)は誰が（どんなユーザが）実行できるのかを設計。
- [ ] 各機能(model)についてissueを切り出す。
  - 切り出したissueには誰が使えるのかを記載する。
  - 各issueの対応で 使えるかどうかを判定する関数の定義・実装 と それをmodel内で利用する2ステップで実行する。

## 進め方 方針

- [ ] ぱっと見でレビューする。 （比較的簡単な機能向け）
- [ ] 必要に応じてペアプロしながら しっかりレビューする。 （相談・調整しながら仕上げていく機能向け）
- [x] その他

チーム全員（主にサーバチーム主導）で設計する。

## 参考文献

-

**Comment by daisonmeganes** [comment]
権限関連まとめ
https://docs.google.com/spreadsheets/d/1XeEypaHZPX73YsBQ6ic_ZhY9tkGyYAMl1im7gr_IwjY/edit#gid=0
