### ISSUE TITLE
共通パーツを実装 - 汎用コンポーネントを components フォルダに作成

### ISSUE THREAD

**Issue by TBSten** [megane-s/minshumi-frontend#32]
## 機能の説明

`/src/components/` ディレクトリ配下にボタンなどの汎用コンポーネントを追加してください。

作成したコンポーネントは `/src/app/debug/page.tsx` にテスト表示しておいてもらえると助かります。

## 実装内容 または やること

 

- [ ] 担当者を決める。
- [ ] 汎用コンポーネントの列挙。
- [ ] 各コンポーネントを実装。

## 進め方 方針

- [ ] ぱっと見でレビューする。 （比較的簡単な機能向け）
- [x] 必要に応じてペアプロしながら しっかりレビューする。 （相談・調整しながら仕上げていく機能向け）
- [ ] その他

## 参考文献

- 画面設計書

**Comment by TBSten** [comment]
## 汎用コンポーネントの列挙

- [ ] ボタン
- [ ] Link (MantineのAnchorとnext/linkを統合)
- [ ]

**Comment by TBSten** [comment]
担当分けてもいいかも。

**Comment by greenmeganes** [comment]
# 担当


@TBSten
- Button
- Link
- Dialog


@greenmeganes 

- Card
- TextInput
- Textarea
- PageTitle
- SectionTitle
- ActionIcon
- Avatar

@daisonmeganes 

- Chip
- Tab
- Loader
- TagsInput
- Badge
- Carousel
- Switch

**Comment by TBSten** [comment]
#67 #68 #69 終了につきclose
