### ISSUE TITLE
本番環境にいくつかメジャーな作品を登録

### ISSUE THREAD

**Issue by TBSten** [megane-s/minshumi-frontend#328]
## アイデアの概要

トップ画面の見栄えがよろしくないので、デフォ画像をランダムにするなどで改善したい

**Comment by TBSten** [comment]
画像は[Figmaのこれ](https://www.figma.com/file/CgUG7Ndac2D6JwWLdVo42i/%E3%81%BF%E3%82%93%E3%81%97%E3%82%85%E3%81%BF-%E7%94%BB%E9%9D%A2%E8%A8%AD%E8%A8%88?type=design&node-id=996-4&mode=design&t=XinTkFZLrALRCbxa-4)などを参考に作って欲しい

**Comment by TBSten** [comment]
トップ画面が綺麗になるのが目的

**Comment by daisonmeganes** [comment]
> トップ画面が綺麗になるのが目的

![スクリーンショット 2024-02-01 164511](https://github.com/megane-s/minshumi-frontend/assets/148510436/b8eddfb9-7a3d-47be-85a7-1392ead1f284)
