### ISSUE TITLE
作品の検索画面の実装

### ISSUE THREAD

**Issue by TBSten** [megane-s/minshumi-frontend#55]
## 機能の説明

No8 作品の検索画面を実装する。

https://docs.google.com/spreadsheets/d/1AswDPFDAM7VYSjl7X__bb_rLWHL6BooKVIOxKPMo8I8/edit#gid=0&range=A10:E10

## 実装内容 または やること

 

- [ ] 担当者を決める

## 進め方 方針

- [x] ぱっと見でレビューする。 （比較的簡単な機能向け）
- [ ] 必要に応じてペアプロしながら しっかりレビューする。 （相談・調整しながら仕上げていく機能向け）
- [ ] その他

## 参考文献

-

**Comment by TBSten** [comment]
サーバチームで検索ロジックが完成したからの方が良さそう。

**Comment by TBSten** [comment]
検索結果は `searchArt()` model 関数を使用して取得できます。

```tsx
const searchResults = await searchArt("検索キーワード")
```

**Comment by greenmeganes** [comment]
全部完了しました。

**Comment by greenmeganes** [comment]
タブにするのを忘れていました。
