### ISSUE TITLE
プロフィール表示画面の実装

### ISSUE THREAD

**Issue by TBSten** [megane-s/minshumi-frontend#58]
## 機能の説明

No11 プロフィール表示画面を実装する。

https://docs.google.com/spreadsheets/d/1AswDPFDAM7VYSjl7X__bb_rLWHL6BooKVIOxKPMo8I8/edit#gid=0&range=A13:E13

## 実装内容 または やること

 

- [x] 担当者を決める

## 進め方 方針

- [x] ぱっと見でレビューする。 （比較的簡単な機能向け）
- [ ] 必要に応じてペアプロしながら しっかりレビューする。 （相談・調整しながら仕上げていく機能向け）
- [ ] その他

## 参考文献

-

**Comment by TBSten** [comment]
[hint]

ユーザの情報は `/src/user/get.ts` の `getUser()` model関数で取得できます。

```tsx
const userId = /* ユーザID */
const user = await getUser(userId)
```

- ユーザのIDを指定してそのユーザの情報を返します。返されるUserオブジェクトの型は以下の通りです。

```tsx
type User = {
    image: string | null;
    id: string;
    name: string | null;
    email: string | null;
    emailVerified: Date | null;
}
```

- ユーザが存在しなかった場合、nullが返されます。

**Comment by TBSten** [comment]
[hint]

名刺は `/src/businessCard/getByUser.ts` の `getBusinessCardByUser()` model関数から取得できます。

- ユーザIDを指定してそのユーザが作った名刺一覧(BusinessCard[])を取得できます。

```tsx
const businessCards = await getBusinessCardByUser(ユーザID)
```

- 名刺(BusinessCard)は以下のようなオブジェクトです。

```tsx
type BusinessCard = {
    businessCardId: string;
    userId: string;
    backgroundImageUrl: string;
    canComment: boolean;
}
```

**Comment by TBSten** [comment]
#81 でテスト用データを用意しました。

**Comment by TBSten** [comment]
#94 でテスト用データを追加しました

**Comment by daisonmeganes** [comment]
まだユーザが見ている作品、好きな作品を登録していないときに
「今見ている（好きな作品）が登録されていません」の表示がほしい
