### ISSUE TITLE
画面設計書をFigmaに移す

### ISSUE THREAD

**Issue by TBSten** [megane-s/minshumi-frontend#74]
## アイデアの概要

[Figma](https://www.figma.com/file/CgUG7Ndac2D6JwWLdVo42i/%E3%81%BF%E3%82%93%E3%81%97%E3%82%85%E3%81%BF-%E7%94%BB%E9%9D%A2%E8%A8%AD%E8%A8%88?type=design&node-id=232%3A2&mode=design&t=GbEWwEoG6m66EnuV-1)

**Comment by daisonmeganes** [comment]
去年に対応済みです
