### ISSUE TITLE
カルーセル実装

### ISSUE THREAD

**Issue by daisonmeganes** [megane-s/minshumi-frontend#77]
## 機能の説明

カルーセルのところむずいのでやる。

#58 

## 実装内容 または やること

 

- [x] 担当者を決める

## 進め方 方針

- [ ] ぱっと見でレビューする。 （比較的簡単な機能向け）
- [x] 必要に応じてペアプロしながら しっかりレビューする。 （相談・調整しながら仕上げていく機能向け）
- [ ] その他

## 参考文献

-

**Comment by TBSten** [comment]
参考
https://mantine.dev/others/carousel/
